### ISSUE TITLE
Thread deadlock on ReactorChannel.java

### ISSUE THREAD

**Issue by tramonex-yilin** [thomsonreuters/Elektron-SDK#20]
Hi,

We're seeing an issue where we are getting a thread deadlock in the `ReactorChannel` when trying to register a ric using the `registerClient` method on the `OmmConsumer`.

We've put `synchronized` blocks whenever we use the `OmmConsumer` (we're we are subscribing/unsubscribing from rics) , but we're still seeing this issue.

Are there any other parts of the SDK which are non-thread safe and would cause this issue?

```
   at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at com.thomsonreuters.upa.valueadd.reactor.ReactorChannel.submit(ReactorChannel.java:494)
        at com.thomsonreuters.ema.access.SingleItem.rsslSubmit(ItemCallbackClient.java:1147)
        at com.thomsonreuters.ema.access.SingleItem.open(ItemCallbackClient.java:1006)
        at com.thomsonreuters.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:540)
        at com.thomsonreuters.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:340)
        at com.thomsonreuters.ema.access.OmmConsumerImpl.registerClient(OmmConsumerImpl.java:70)

```

**Comment by maydu** [comment]
Hi,
Does your application use OperationModel.USER_DISPATCH or OperationModel.API_DISPATCH? You can try to use OperationModel.USER_DISPATCH to see if the thread deadlock goes away. You can find out how to use OperationModel.USER_DISPATCH from example130_MarketPrice_UserDisp in the package

**Comment by BrianSandri** [comment]
@tramonex-yilin Is this issue still impacting you?  Do you have any answers to the above questions from @maydu?  Have you been able to try the new 3.1 release and does that still exhibit the issue?  We want to be sure your issue is addressed.  Thanks!
