### ISSUE TITLE
EMA NIP Dictionary request from ADH throws exception

### ISSUE THREAD

**Issue by gardida** [thomsonreuters/Elektron-SDK#32]
I have implemented a NIP using the EMA Java libs (latest build 3.1.0.L1-SNAPSHOT).

When attempting to make a request for the dictionary from ADH via the below

```
long fldHandle = provider.registerClient(EmaFactory.createReqMsg().domainType(EmaRdm.MMT_DICTIONARY)
					.name("RWFFld").filter(EmaRdm.DICTIONARY_NORMAL), appClient);
```
					
where appClient implements OmmProviderClient

I receive a nullPointerException

Exception in thread "main" java.lang.NullPointerException
```
	at com.thomsonreuters.ema.access.DictionaryItem.open(DictionaryCallbackClient.java:1126)
	at com.thomsonreuters.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:1719)
	at com.thomsonreuters.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:363)
	at com.thomsonreuters.ema.access.OmmNiProviderImpl.registerClient(OmmNiProviderImpl.java:201)
	at com.thomsonreuters.ema.access.OmmNiProviderImpl.registerClient(OmmNiProviderImpl.java:193)
	at com.rbs.trep.NiProvider.main(NiProvider.java:72)
```
	
The exception appears to happen before the request has even been made to the ADH ie its on the application side.	

Another user has confimed they have the same issue
https://community.developers.thomsonreuters.com/questions/16675/ema-nip-dictionary-request.html?childToView=16716

Can you advise if this is a bug or an error with the way I have implemented the request?

thanks

**Comment by soranat** [comment]
For NIP, EMA Java and C++ does not support the dictionary download feature from the ADH yet.

The tracking number ESDK-462 is used to capture this issue.

**Comment by soranat** [comment]
The enhancement for supporting the dictionary download feature for Non-Interactive and Interactive providers from the ADH has been added into Elektron-SDK_1.1.1 release. Thanks for your support.
