### ISSUE TITLE
EMA ChannelSet failover exception

### ISSUE THREAD

**Issue by gardida** [thomsonreuters/Elektron-SDK#44]
I'm using EMA Java 1.1.1 and testing the ChannelSet failover behaviour on a NIP.
If the application does failover to the second ADH, the application encounters the below exception when the API sends Dictionary Request message to the second ADH.
(I raised this on the forums as well https://community.developers.thomsonreuters.com/questions/23010/ema-channelset-failover.html)

Please exception messages below:
Jan 11, 2018 6:13:06 PM com.thomsonreuters.ema.access.ChannelCallbackClient reactorChannelEventCallback
WARNING: loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Warning
    Text:    Received ChannelDownReconnecting event on channel Channel_1
    RsslReactor Channel is null
    Error Id 0
    Internal sysError 0
    Error Location Reactor.processWorkerEvent
    Error text Error initializing channel: errorId=-1 text=Connection refused: no further information
loggerMsgEnd

Jan 11, 2018 6:13:07 PM com.thomsonreuters.ema.access.ChannelCallbackClient reactorChannelEventCallback
INFO: loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Info
    Text:    Received ChannelUp event on channel Channel_3
    Instance Name Provider_1_1
    Component Version adh3.2.0.L1.linux.tis.rrg 64-bit
loggerMsgEnd

Exception in thread "main" java.lang.NullPointerException
    at com.thomsonreuters.ema.access.NiProviderDictionaryItem.rsslSubmit(DictionaryCallbackClient.java:1920)
    at com.thomsonreuters.ema.access.NiProviderDictionaryItem.open(DictionaryCallbackClient.java:1777)
    at com.thomsonreuters.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:1990)
    at com.thomsonreuters.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:380)
    at com.thomsonreuters.ema.access.OmmNiProviderImpl.registerClient(OmmNiProviderImpl.java:280)
    at com.thomsonreuters.ema.access.OmmNiProviderImpl.registerClient(OmmNiProviderImpl.java:263)
    at com.thomsonreuters.ema.examples.training.niprovider.series300.example350__Dictionary__Streaming.NiProvider.main(NiProvider.java:135)

**Comment by bberner** [comment]
We have created a JIRA issue for this and the fix will be in a future release.

**Comment by bberner** [comment]
This issue has been fixed in the ESDK 1.2.0 release.
