### ISSUE TITLE
Null pointer exception when trying to perform client login to TRCC

### ISSUE THREAD

**Issue by narcissuhk** [thomsonreuters/Elektron-SDK#50]
Hi all,

I am trying to use Java version of EMA to post data to TRCC.

> chp01-eap-emea1.thomsonreuters.com:443

Since no Java documentation is available, I am trying to follow the C++ tutorial.
https://developers.thomsonreuters.com/elektron/elektron-sdk-cc/learning?content=26452&type=learning_material_item

When I try to perform a client login, it throws a null pointer exception.

> Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at com.thomsonreuters.ema.access.TunnelItem.addSubItem(ItemCallbackClient.java:279)
	at com.thomsonreuters.ema.access.SubItem.open(ItemCallbackClient.java:886)
	at com.thomsonreuters.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:2180)
	at com.thomsonreuters.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:338)
	at com.thomsonreuters.ema.access.OmmConsumerImpl.registerClient(OmmConsumerImpl.java:114)
	at com.thomsonreuters.ema.examples.training.consumer.series300.example341__MarketPrice__OffStreamPost.AppClient.onStatusMsg(Consumer.java:130)
	at com.thomsonreuters.ema.access.ItemCallbackClientConsumer.notifyOnStatusMsg(ItemCallbackClient.java:2514)
	at com.thomsonreuters.ema.access.ItemCallbackClient.statusEventCallback(ItemCallbackClient.java:1133)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.sendTunnelStreamStatusEventCallback(Reactor.java:932)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.sendAndHandleTunnelStreamStatusEventCallback(Reactor.java:944)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.handleTunnelStreamMsg(Reactor.java:3660)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.sendAndHandleDefaultMsgCallback(Reactor.java:821)
	at com.thomsonreuters.upa.valueadd.reactor.WlItemHandler.callbackUser(WlItemHandler.java:2708)
	at com.thomsonreuters.upa.valueadd.reactor.WlItemHandler.readRefreshMsg(WlItemHandler.java:2004)
	at com.thomsonreuters.upa.valueadd.reactor.WlItemHandler.readMsg(WlItemHandler.java:1735)
	at com.thomsonreuters.upa.valueadd.reactor.Watchlist.readMsg(Watchlist.java:277)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.performChannelRead(Reactor.java:1758)
	at com.thomsonreuters.upa.valueadd.reactor.Reactor.dispatchChannel(Reactor.java:1389)
	at com.thomsonreuters.upa.valueadd.reactor.ReactorChannel.dispatch(ReactorChannel.java:469)
	at com.thomsonreuters.ema.access.OmmBaseImpl.rsslReactorDispatchLoop(OmmBaseImpl.java:1128)
	at com.thomsonreuters.ema.access.OmmBaseImpl.run(OmmBaseImpl.java:1261)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

where AppClient.onStatusMessage
```
            ElementList elementList = EmaFactory.createElementList();
            ElementEntry elementEntry = EmaFactory.createElementEntry();
            elementEntry.ascii("Password", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

            ReqMsg reqMsg = EmaFactory.createReqMsg();
            reqMsg.domainType(EmaRdm.MMT_SYSTEM)
                    .name("GEM-XXX-XXXXXX")
                    .privateStream(true)
                    .attrib(elementList)
                    .streamId(statusMsg.streamId());

            System.out.println("Submit GenericMsg from onStatus");

            subStreamHandle = ommConsumer.registerClient(reqMsg, this, 1, tunnelStreamHandle);
```
Is there any problems? Or am i doing anything wrong?
It will be great if someone could give me a hint on it.
Thanks.

**Comment by bberner** [comment]
Thanks for bringing this to our attention. This is a bug we're already aware of and it will be fixed in the next release. If you need the fix sooner, you can substitute the following code for com.thomsonreuters.ema.access.TunnelItem.addSubItem(ItemCallbackClient.java:279).

if ((streamId < _subItems.size()) && (_subItems.get(streamId) != null))

**Comment by ongilgil** [comment]
Hi bberner,

We followed instructions and we finally connected successfully. But then we got this error:

"Session token renewal request is rejected by AAA." and "Service not available"

Then, we tried the following code suggested (from your company):

old  Version:
ElementList elementList = EmaFactory.createElementList();
            ElementEntry elementEntry = EmaFactory.createElementEntry();
            elementEntry.ascii("Password", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
 
            ReqMsg reqMsg = EmaFactory.createReqMsg();
            reqMsg.domainType(EmaRdm.MMT_SYSTEM)
                    .name("GEM-XXX-XXXXXX")
                    .privateStream(true)
                    .attrib(elementList)
                    .streamId(statusMsg.streamId());
 
changed Version:
 
ElementList elementList = EmaFactory.createElementList();
            ElementEntry elementEntry = EmaFactory.createElementEntry();
            elementEntry.ascii("Password", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
 
            ReqMsg reqMsg = EmaFactory.createReqMsg();
            reqMsg.domainType(EmaRdm.MMT_SYSTEM)
                    .name("GEM-XXX-XXXXXX")
                    .privateStream(true)
                    .attrib(elementList)
                    .streamId(0);


But still failed.

Would you please let us know what we could do next?

Thanks.

Rgds,
Gil

**Comment by bberner** [comment]
Please contact TRCC support for more help with this issue. It sounds like a system issue and is outside the scope of ESDK developer support.
