### ISSUE TITLE
Java ETA RsslSocketChannel::write never returns

### ISSUE THREAD

**Issue by DzianisKorshak** [thomsonreuters/Elektron-SDK#88]
We use `Channel::write` method to send a request to HMDS. This method should return a `TransportReturnCode` to indicate successful write or any write failure. But there is an extremely rare case when `Channel::write` method does not return anything. The thread invoking that method becomes Running forever (waiting `Channel::write` to return control).

It is a critical issue for our application. As you will see from a stack trace attached particular thread acquired a lock before writing to the Channel and never release it. Thus our application becomes unable to send any subsequent request to HMDS.

According to documentation for Channel::write method:  

> If blocking I/O is used, the write method will not return until data was written to the connection or an error has occurred.

But we are using non-blocking I/O; and I didn’t find any other cases when `Channel::write` may not return control.
 
Could you please assist us on that issue? We observe it on everyday basis.

Below you may find our configuration and stack trace for the Thread running `Channel::write` method.
Elektron SDK artifacts:
```
<dependency>
    <groupId>com.thomsonreuters.eta</groupId>
    <artifactId>upa</artifactId>
    <version>3.2.1.L0</version>
</dependency>
<dependency>
    <groupId>com.thomsonreuters.eta</groupId>
    <artifactId>upaValueAdd</artifactId>
    <version>3.2.1.L0</version>
</dependency>
```
Configuration:
```
ConnectOptions copts = TransportFactory.createConnectOptions();
copts.numInputBuffers(350);
copts.guaranteedOutputBuffers(500);
copts.majorVersion(Codec.majorVersion());
copts.minorVersion(Codec.minorVersion());
copts.protocolType(Codec.protocolType());
copts.blocking(false);
```
```
InitArgs initArgs = TransportFactory.createInitArgs();
initArgs.globalLocking(true);
```
```
WriteArgs writeArgs = TransportFactory.createWriteArgs();
writeArgs.clear();
writeArgs.priority(WritePriorities.HIGH);
writeArgs.flags(WriteFlags.DIRECT_SOCKET_WRITE);
```
Stack trace:
```
"pool-17-thread-2" #61 prio=5 os_prio=0 tid=0x000000002900a000 nid=0x3974 runnable [0x000000002fd4d000]
   java.lang.Thread.State: RUNNABLE
                at com.thomsonreuters.upa.transport.RsslSocketChannel.fillGatheringByteArray(RsslSocketChannel.java:2620)
                at com.thomsonreuters.upa.transport.RsslSocketChannel.flushInternal(RsslSocketChannel.java:2559)
                at com.thomsonreuters.upa.transport.RsslSocketChannel.writeWithNoBuffersQueued(RsslSocketChannel.java:2437)
                at com.thomsonreuters.upa.transport.RsslSocketChannel.write(RsslSocketChannel.java:2198)
                at com.tr.apt.data.access.elektron.upa.common.ChannelSession.write(ChannelSession.java:495)
                at com.tr.apt.data.access.elektron.upa.common.ChannelSession.sendMsg(ChannelSession.java:233)
                at com.tr.apt.data.access.elektron.upa.common.MarketPriceHandler.sendRequest(MarketPriceHandler.java:211)
                - locked <0x00000006c456f1f8> (a com.tr.apt.data.access.elektron.upa.shared.rdm.marketprice.MarketPriceRequest)
                at com.tr.apt.data.access.elektron.upa.common.MarketPriceHandler.sendItemRequests(MarketPriceHandler.java:183)
                at com.tr.apt.data.access.elektron.upa.SimpleConsumer.sendMarketPriceRequest(SimpleConsumer.java:670)
                at com.tr.apt.data.access.elektron.upa.SimpleConsumer.getMarketPriceResponses(SimpleConsumer.java:798)
                at com.tr.apt.data.access.elektron.MarketPriceDAO.getInternal(MarketPriceDAO.java:68)
                at com.tr.apt.data.access.elektron.MarketPriceDAO.getInternal(MarketPriceDAO.java:1)

```

**Comment by ckrish** [comment]
Regarding 
copts.channelWriteLocking(true);

Is the above used as a hint for channel to not wait for other threads to fill up the internal queues and flush immediately?

**Comment by bberner** [comment]
Refer to the ETA Java Developers guide section 9.2.3Transport Locking Models for information about ETA locking options. Generally, the channel write lock is used to protect any resources that are shared within a single connection or channel.

**Comment by DzianisKorshak** [comment]
Enabling copts.channelWriteLocking(true) did not help to avoid this issue.
After deeper investigation I can confirm that at some point of time all the priority queues (_hightPriorityQueue, _mediumPriorityQueue and _lowPriorityQueue) in _flushOrder array are empty. At the same time the Channel state remains Active. That's why RsslSocketChannel::fillGatheringByteArray method becomes unable to obtain a TransportBufferImpl instance. The method invocation ends up with waiting for the buffer in an infinity loop.

**Comment by DzianisKorshak** [comment]
Thanks for your collaboration on fixing this issue. I confirm the issue is no longer reproducible in our service.
The root cause of such behavior of ETAJ client was sharing the same EncodeIterator instance across multiple threads without any synchronization on this. During Message encoding operation a RuntimeException was thrown and TransportBuffer instance used to store encoded message has never been released back to the pool. At some point of time all the UpaQueue instances in _flushOrder array become empty and ETAJ client simply unable to flush the message to the channel.
