### ISSUE TITLE
Cold standby not implemented in EMA/Java

### ISSUE THREAD

**Issue by steve-o** [thomsonreuters/Elektron-SDK#9]
After 45s the OmmConsumer reports an error and the Reactor shuts down.

```
2016-05-09 20:45:55,407 ERROR [main] OmmConsumerImpl(OmmConsumerImpl.java:1132): loggerMsg
    ClientName: X_1
    Severity: Error
    Text:    login failed (timed out after waiting 45000 milliseconds) for nylabads2:14002)
loggerMsgEnd


2016-05-09 20:46:05,410 ERROR [main] OmmConsumerImpl(ChannelCallbackClient.java:442): loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Error
    Text:    Received ChannelDown event on channel Y
	Consumer Name X_1
	RsslReactor @7b227d8d
	RsslChannel @3d680b5a
	Error Id 0
	Internal sysError 0
	Error Location null
	Error text Reactor shutting down...
loggerMsgEnd


Exception in thread "main" Exception Type='OmmInvalidUsageException', Text='login failed (timed out after waiting 45000 milliseconds) for nylabads2:14002)'
	at com.thomsonreuters.ema.access.OmmConsumerImpl.ommIUExcept(OmmConsumerImpl.java:945)
	at com.thomsonreuters.ema.access.OmmConsumerImpl.handleAdminReqTimeout(OmmConsumerImpl.java:1134)
	at com.thomsonreuters.ema.access.OmmConsumerImpl.initialize(OmmConsumerImpl.java:196)
	at com.thomsonreuters.ema.access.OmmConsumerImpl.<init>(OmmConsumerImpl.java:91)
	at com.thomsonreuters.ema.access.EmaFactory.createOmmConsumer(EmaFactory.java:158)
	at Consumer.<init>(Consumer.java:143)
	at Consumer.main(Consumer.java:151)
```

**Comment by andrzejczop** [comment]
Steve,

The OmmConsumer throws an invalid usage exception when it times out in the constructor waiting for the login or connection up event. This is a built in behavior. Does your app handle exceptions?
Please post the code of your app to see if everything is "as designed".

**Comment by steve-o** [comment]
Why is the design of EMA/Java different from EMA/C++ which does support cold standby?

```
loggerMsg
    TimeStamp: 16:09:03.555
    ClientName: ChannelCallbackClient
    Severity: Warning
    Text:    Received ChannelDownReconnecting event on channel Channel_1
        Consumer Name Consumer_1_1
        RsslReactor 0x000001DC287E5FF0
        RsslChannel 0x000001DC287E5FF0
        Error Id -1
        Internal sysError 10057
        Error Location ..\..\..\ValueAdd\Reactor\Impl\rsslReactorWorker.c:438
        Error Text <..\..\..\Ripc\Impl\ripcsrvr.c:5160> ripcConnecting() Error: 1002 client connect() failed.  System errno: (10057)
loggerMsgEnd

loggerMsg
    TimeStamp: 16:09:05.617
    ClientName: ChannelCallbackClient
    Severity: Warning
    Text:    Received ChannelDownReconnecting event on channel Channel_2
        Consumer Name Consumer_1_1
        RsslReactor 0x000001DC287E5FF0
        RsslChannel 0x000001DC287E5FF0
        Error Id -1
        Internal sysError 10057
        Error Location ..\..\..\ValueAdd\Reactor\Impl\rsslReactorWorker.c:438
        Error Text <..\..\..\Ripc\Impl\ripcsrvr.c:5160> ripcConnecting() Error: 1002 client connect() failed.  System errno: (10057)
loggerMsgEnd
```

**Comment by andrzejczop** [comment]
Steve,

to answer your question about the "cold standby support" in the EMA Java....

In general the EMA C++ and EMA Java will provide the same functionalities / features.
So the "cold standby" or rather the "channelSet" feature will be supported by the EMA Java as well.

We are working on it.

**Comment by GregLee-TR** [comment]
This is captured as with JIRA EMA-365 and in our backlog.  The intent is to line up the EMA features set across languages. Thanks!
